// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerInput.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PlayerMsg {

  /// <summary>Holder for reflection information generated from PlayerInput.proto</summary>
  public static partial class PlayerInputReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerInput.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerInputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQbGF5ZXJJbnB1dC5wcm90bxIJUGxheWVyTXNnIqIBCg9Nc2dfUGxheWVy",
            "SW5wdXQSEQoJbW91c2VQb3NYGAEgASgCEhEKCW1vdXNlUG9zWRgCIAEoAhIQ",
            "CghpbnB1dFVWWBgDIAEoAhIQCghpbnB1dFVWWRgEIAEoAhITCgtpc0lucHV0",
            "RmlyZRgFIAEoCBIPCgdza2lsbElkGAYgASgFEhEKCWlzU3BlZWRVcBgHIAEo",
            "CBIMCgR0aWNrGAggASgFIkoKDk1zZ19GcmFtZUlucHV0EgwKBHRpY2sYASAB",
            "KAUSKgoGaW5wdXRzGAIgAygLMhouUGxheWVyTXNnLk1zZ19QbGF5ZXJJbnB1",
            "dGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerMsg.Msg_PlayerInput), global::PlayerMsg.Msg_PlayerInput.Parser, new[]{ "MousePosX", "MousePosY", "InputUVX", "InputUVY", "IsInputFire", "SkillId", "IsSpeedUp", "Tick" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerMsg.Msg_FrameInput), global::PlayerMsg.Msg_FrameInput.Parser, new[]{ "Tick", "Inputs" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Msg_PlayerInput : pb::IMessage<Msg_PlayerInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Msg_PlayerInput> _parser = new pb::MessageParser<Msg_PlayerInput>(() => new Msg_PlayerInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Msg_PlayerInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerMsg.PlayerInputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_PlayerInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_PlayerInput(Msg_PlayerInput other) : this() {
      mousePosX_ = other.mousePosX_;
      mousePosY_ = other.mousePosY_;
      inputUVX_ = other.inputUVX_;
      inputUVY_ = other.inputUVY_;
      isInputFire_ = other.isInputFire_;
      skillId_ = other.skillId_;
      isSpeedUp_ = other.isSpeedUp_;
      tick_ = other.tick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_PlayerInput Clone() {
      return new Msg_PlayerInput(this);
    }

    /// <summary>Field number for the "mousePosX" field.</summary>
    public const int MousePosXFieldNumber = 1;
    private float mousePosX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MousePosX {
      get { return mousePosX_; }
      set {
        mousePosX_ = value;
      }
    }

    /// <summary>Field number for the "mousePosY" field.</summary>
    public const int MousePosYFieldNumber = 2;
    private float mousePosY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MousePosY {
      get { return mousePosY_; }
      set {
        mousePosY_ = value;
      }
    }

    /// <summary>Field number for the "inputUVX" field.</summary>
    public const int InputUVXFieldNumber = 3;
    private float inputUVX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float InputUVX {
      get { return inputUVX_; }
      set {
        inputUVX_ = value;
      }
    }

    /// <summary>Field number for the "inputUVY" field.</summary>
    public const int InputUVYFieldNumber = 4;
    private float inputUVY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float InputUVY {
      get { return inputUVY_; }
      set {
        inputUVY_ = value;
      }
    }

    /// <summary>Field number for the "isInputFire" field.</summary>
    public const int IsInputFireFieldNumber = 5;
    private bool isInputFire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsInputFire {
      get { return isInputFire_; }
      set {
        isInputFire_ = value;
      }
    }

    /// <summary>Field number for the "skillId" field.</summary>
    public const int SkillIdFieldNumber = 6;
    private int skillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    /// <summary>Field number for the "isSpeedUp" field.</summary>
    public const int IsSpeedUpFieldNumber = 7;
    private bool isSpeedUp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSpeedUp {
      get { return isSpeedUp_; }
      set {
        isSpeedUp_ = value;
      }
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 8;
    private int tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Msg_PlayerInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Msg_PlayerInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MousePosX, other.MousePosX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MousePosY, other.MousePosY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InputUVX, other.InputUVX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InputUVY, other.InputUVY)) return false;
      if (IsInputFire != other.IsInputFire) return false;
      if (SkillId != other.SkillId) return false;
      if (IsSpeedUp != other.IsSpeedUp) return false;
      if (Tick != other.Tick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MousePosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MousePosX);
      if (MousePosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MousePosY);
      if (InputUVX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InputUVX);
      if (InputUVY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InputUVY);
      if (IsInputFire != false) hash ^= IsInputFire.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (IsSpeedUp != false) hash ^= IsSpeedUp.GetHashCode();
      if (Tick != 0) hash ^= Tick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MousePosX != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(MousePosX);
      }
      if (MousePosY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MousePosY);
      }
      if (InputUVX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(InputUVX);
      }
      if (InputUVY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(InputUVY);
      }
      if (IsInputFire != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsInputFire);
      }
      if (SkillId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SkillId);
      }
      if (IsSpeedUp != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsSpeedUp);
      }
      if (Tick != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Tick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MousePosX != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(MousePosX);
      }
      if (MousePosY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MousePosY);
      }
      if (InputUVX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(InputUVX);
      }
      if (InputUVY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(InputUVY);
      }
      if (IsInputFire != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsInputFire);
      }
      if (SkillId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SkillId);
      }
      if (IsSpeedUp != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsSpeedUp);
      }
      if (Tick != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Tick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MousePosX != 0F) {
        size += 1 + 4;
      }
      if (MousePosY != 0F) {
        size += 1 + 4;
      }
      if (InputUVX != 0F) {
        size += 1 + 4;
      }
      if (InputUVY != 0F) {
        size += 1 + 4;
      }
      if (IsInputFire != false) {
        size += 1 + 1;
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      if (IsSpeedUp != false) {
        size += 1 + 1;
      }
      if (Tick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Msg_PlayerInput other) {
      if (other == null) {
        return;
      }
      if (other.MousePosX != 0F) {
        MousePosX = other.MousePosX;
      }
      if (other.MousePosY != 0F) {
        MousePosY = other.MousePosY;
      }
      if (other.InputUVX != 0F) {
        InputUVX = other.InputUVX;
      }
      if (other.InputUVY != 0F) {
        InputUVY = other.InputUVY;
      }
      if (other.IsInputFire != false) {
        IsInputFire = other.IsInputFire;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      if (other.IsSpeedUp != false) {
        IsSpeedUp = other.IsSpeedUp;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            MousePosX = input.ReadFloat();
            break;
          }
          case 21: {
            MousePosY = input.ReadFloat();
            break;
          }
          case 29: {
            InputUVX = input.ReadFloat();
            break;
          }
          case 37: {
            InputUVY = input.ReadFloat();
            break;
          }
          case 40: {
            IsInputFire = input.ReadBool();
            break;
          }
          case 48: {
            SkillId = input.ReadInt32();
            break;
          }
          case 56: {
            IsSpeedUp = input.ReadBool();
            break;
          }
          case 64: {
            Tick = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            MousePosX = input.ReadFloat();
            break;
          }
          case 21: {
            MousePosY = input.ReadFloat();
            break;
          }
          case 29: {
            InputUVX = input.ReadFloat();
            break;
          }
          case 37: {
            InputUVY = input.ReadFloat();
            break;
          }
          case 40: {
            IsInputFire = input.ReadBool();
            break;
          }
          case 48: {
            SkillId = input.ReadInt32();
            break;
          }
          case 56: {
            IsSpeedUp = input.ReadBool();
            break;
          }
          case 64: {
            Tick = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Msg_FrameInput : pb::IMessage<Msg_FrameInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Msg_FrameInput> _parser = new pb::MessageParser<Msg_FrameInput>(() => new Msg_FrameInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Msg_FrameInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerMsg.PlayerInputReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_FrameInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_FrameInput(Msg_FrameInput other) : this() {
      tick_ = other.tick_;
      inputs_ = other.inputs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg_FrameInput Clone() {
      return new Msg_FrameInput(this);
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 1;
    private int tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    /// <summary>Field number for the "inputs" field.</summary>
    public const int InputsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::PlayerMsg.Msg_PlayerInput> _repeated_inputs_codec
        = pb::FieldCodec.ForMessage(18, global::PlayerMsg.Msg_PlayerInput.Parser);
    private readonly pbc::RepeatedField<global::PlayerMsg.Msg_PlayerInput> inputs_ = new pbc::RepeatedField<global::PlayerMsg.Msg_PlayerInput>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PlayerMsg.Msg_PlayerInput> Inputs {
      get { return inputs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Msg_FrameInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Msg_FrameInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tick != other.Tick) return false;
      if(!inputs_.Equals(other.inputs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Tick != 0) hash ^= Tick.GetHashCode();
      hash ^= inputs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Tick != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Tick);
      }
      inputs_.WriteTo(output, _repeated_inputs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Tick != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Tick);
      }
      inputs_.WriteTo(ref output, _repeated_inputs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Tick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tick);
      }
      size += inputs_.CalculateSize(_repeated_inputs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Msg_FrameInput other) {
      if (other == null) {
        return;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      inputs_.Add(other.inputs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Tick = input.ReadInt32();
            break;
          }
          case 18: {
            inputs_.AddEntriesFrom(input, _repeated_inputs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Tick = input.ReadInt32();
            break;
          }
          case 18: {
            inputs_.AddEntriesFrom(ref input, _repeated_inputs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
