// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoCode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpCode {

  /// <summary>Holder for reflection information generated from ProtoCode.proto</summary>
  public static partial class ProtoCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoCode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0NvZGUucHJvdG8SBk9wQ29kZSpxCglQcm90b0NvZGUSDgoKU19K",
            "b2luUm9vbRAAEg4KClNfUXVpdFJvb20QARIPCgtTX1N0YXJ0R2FtZRACEhEK",
            "DVNfUGxheWVySW5wdXQQAxIQCgxTX0ZyYW1lSW5wdXQQBBIOCgpTX0hhc2hD",
            "b2RlEAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpCode.ProtoCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoCode {
    /// <summary>
    ///加入房间
    /// </summary>
    [pbr::OriginalName("S_JoinRoom")] SJoinRoom = 0,
    /// <summary>
    ///离开房间
    /// </summary>
    [pbr::OriginalName("S_QuitRoom")] SQuitRoom = 1,
    /// <summary>
    ///开始游戏
    /// </summary>
    [pbr::OriginalName("S_StartGame")] SStartGame = 2,
    /// <summary>
    ///用户输入提交
    /// </summary>
    [pbr::OriginalName("S_PlayerInput")] SPlayerInput = 3,
    /// <summary>
    ///帧输入(?)
    /// </summary>
    [pbr::OriginalName("S_FrameInput")] SFrameInput = 4,
    /// <summary>
    ///帧校验哈希
    /// </summary>
    [pbr::OriginalName("S_HashCode")] SHashCode = 5,
  }

  #endregion

}

#endregion Designer generated code
